brace_style = "PreferSameLine"
comment_width = 100
condense_wildcard_suffixes = true
force_multiline_blocks = true
indent_style = "Visual"
max_width = 120
normalize_comments = true
reorder_imports = true
reorder_imports_in_group = true
use_try_shorthand = true
