#
# Copyright (C) 2017, 2018 O.S. Systems Sofware LTDA
#
# SPDX-License-Identifier: MPL-2.0
#

[package]
name = "updatehub"
version = "0.1.0"
authors = ["Otavio Salvador <otavio@ossystems.com.br>"]
license = "MPL-2.0"

[dependencies]
app = "0.6.3"
checked_command = "0.2.2"
chrono = { version = "0.4", features = ["serde"] }
clippy = { version = "0.0.179", optional = true }
cmdline_words_parser = "0.0.2"
crypto-hash = "0.3.0"
failure = "0.1.1"
failure_derive = "0.1.1"
hyper = "0.11.16"
log = "0.4"
parse_duration = "1.0"
reqwest = "0.8.4"
serde = "1.0"
serde_derive = "1.0"
serde_ini = "0.1"
serde_json = "1.0"
stderrlog = "0.2.3"
rand = "0.4"
walkdir = "2"

[build-dependencies]
git-version = "0.1.2"

[dev-dependencies]
mktemp = "0.3.1"
mockito = "0.9.0"
