#
# Copyright (C) 2017, 2018 O.S. Systems Sofware LTDA
#
# SPDX-License-Identifier: MPL-2.0
#

[package]
name = "updatehub"
version = "0.1.0"
authors = ["Otavio Salvador <otavio@ossystems.com.br>"]
license = "MPL-2.0"

[dependencies]
app = "0.6.5"
checked_command = "0.2.2"
chrono = { version = "0.4.2", features = ["serde"] }
cmdline_words_parser = "0.0.2"
crypto-hash = "0.3.1"
failure = "0.1.1"
failure_derive = "0.1.1"
hex = "0.3.2"
hyper = "0.11.25"
log = "0.4.1"
parse_duration = "1.0.1"
reqwest = "0.8.5"
serde = "1.0.44"
serde_derive = "1.0.44"
serde_ini = "0.1.3"
serde_json = "1.0.17"
stderrlog = "0.4.0"
rand = "0.4.2"
walkdir = "2.1.4"

[build-dependencies]
git-version = "0.2.0"

[dev-dependencies]
mktemp = "0.3.1"
mockito = "0.9.1"
