#
# Copyright (C) 2017, 2018 O.S. Systems Sofware LTDA
#
# SPDX-License-Identifier: GPL-2.0-only
#

[package]
name = "updatehub"
version = "0.1.0"
authors = ["Otavio Salvador <otavio@ossystems.com.br>"]
license = "GPL-2.0-only"

[dependencies]
app = "0.6.3"
checked_command = "0.2.2"
chrono = { version = "0.4", features = ["serde"] }
clippy = { version = "0.0.179", optional = true }
cmdline_words_parser = "0.0.2"
failure = "0.1.1"
failure_derive = "0.1.1"
log = "0.4"
parse_duration = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_ini = "0.1"
stderrlog = "0.2.3"
walkdir = "2"

[build-dependencies]
git-version = "0.1.2"

[dev-dependencies]
mktemp = "0.3.1"

