#
# Copyright (C) 2017, 2018 O.S. Systems Sofware LTDA
#
# SPDX-License-Identifier: MPL-2.0
#

[package]
name = "updatehub"
version = "0.1.0"
authors = ["Otavio Salvador <otavio@ossystems.com.br>"]
license = "MPL-2.0"

[dependencies]
app = "*"
checked_command = "*"
chrono = { version = "*", features = ["serde"] }
clippy = { version = "*", optional = true }
cmdline_words_parser = "*"
crypto-hash = "*"
failure = "*"
failure_derive = "*"
hyper = "*"
log = "*"
parse_duration = "*"
reqwest = "*"
serde = "*"
serde_derive = "*"
serde_ini = "*"
serde_json = "*"
stderrlog = "*"
rand = "*"
walkdir = "*"

[build-dependencies]
git-version = "*"

[dev-dependencies]
mktemp = "*"
mockito = "*"
